apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-state-management-http
  labels:
    app: node-state-management-http-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-state-management-http-app
  template:
    metadata:
      labels:
        app: node-state-management-http-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "node-state-management-http-app"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: node-state-management-http-app
        image: dapr-node-statemanagement-http:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: "IfNotPresent"